steps:
  # Step 0 - Build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/my-practice-project-443208/ci-cd-gcp-example/testwebserver:v1', '.' ]

  # Step 1 - Run unit tests inside the docker container
  - name: 'europe-west1-docker.pkg.dev/just-amp-373710/ci-cd-gcp-example/testwebserver:v1'
    entrypoint: python
    args: ["-m", "pytest", "."]

  # Step 2 - Push the docker image to be used by Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/my-practice-project-443208/ci-cd-gcp-example/testwebserver:v1']

  # Step 3 - Deploy the image in a cloud run container
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrunservice'
      - '--image'
      - 'europe-west1-docker.pkg.dev/my-practice-project-443208/ci-cd-gcp-example/testwebserver:v1'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'

# Specify the Cloud Storage bucket for build logs
options:
  logging: CLOUD_LOGGING_ONLY   # You can choose CLOUD_LOGGING_ONLY, NONE, or the default logging options
  logs_bucket: "gs://your-log-bucket-name"   # Replace with your bucket name

# You can also specify the service account here if needed:
# service_account: "projects/your-project-id/serviceAccounts/your-service-account@your-project-id.iam.gserviceaccount.com"
